variables:
  # When using dind, it's wise to use the overlayfs driver for improved performance.
  DOCKER_DRIVER: overlay2
  #
  # We need to set this so that docker (client) connects to the dind
  # service on port 2376. This is required when we need to use TLS,
  # which is the now recommended way to run the dind service.
  DOCKER_TLS_VERIFY: 1
  #
  # This instructs the docker client on where to find the appropriate certificates
  # used to handle the condition listed here above.
  DOCKER_CERT_PATH: /certs/client/


stages:
  - build


###############################################
##  Generic template for container building  ##
###############################################
.generic:
  image: docker:latest
  services:
    - name: ${CI_REGISTRY}/dockers/ci/docker:dind
      alias: docker
  variables:
    INTERNAL_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_JOB_NAME}"
    PUBLIC_IMAGE: "${DOCKERHUB_LOGIN}/${CI_JOB_NAME}"
  tags:
    - dind
  before_script:
    - export TOR_VER="${CI_JOB_NAME#*:}"
    - docker login -u "${DOCKERHUB_LOGIN}" -p "${DOCKERHUB_TOKEN}"
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker buildx install
  script:
    - docker build --build-arg TOR_VER="${TOR_VER}" -t "${CI_JOB_NAME}" .
    - docker tag "${CI_JOB_NAME}" "${INTERNAL_IMAGE}"
    - docker tag "${CI_JOB_NAME}" "${PULIC_IMAGE}"
    - docker push "${INTERNAL_IMAGE}"
    - docker push "${PUBLIC_IMAGE}"
  after_script:
    - docker logout "${CI_REGISTRY}"


###############################################
##  The only stage of our container          ##
###############################################
.generic-build:
  extends: .generic
  stage: build

tor-client:0.4.5.16:
  extends: .generic-build

tor-client:0.4.6.12:
  extends: .generic-build

tor-client:0.4.7.16:
  extends: .generic-build

tor-client:0.4.8.10:
  extends: .generic-build
